// <auto-generated />
namespace CODEFİRST_YTU.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class den2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(den2));
        
        string IMigrationMetadata.Id
        {
            get { return "202312072128313_den2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
